project:
  type: website
  output-dir: docs

website:
  title: "Thoughts on Rates. Autumn 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - thoughts_pt1.qmd
      - thoughts_pt2.qmd
      - thoughts_pt3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



